modulelist=com.liferay.referenceschecker.querieslistener.agent.QueriesListenerAgentFactory
eventlisteners=com.liferay.referenceschecker.listener.ReferencesCheckerInfrastructureListener
driverlist=
autoflush=false