/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.customer.license.model.LicenseKeySet;
import com.liferay.osb.customer.license.model.LicenseKeySetModel;
import com.liferay.osb.customer.license.model.LicenseKeySetSoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LicenseKeySet service. Represents a row in the &quot;OSB_LicenseKeySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LicenseKeySetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeySetImpl
 * @generated
 */
@JSON(strict = true)
public class LicenseKeySetModelImpl
	extends BaseModelImpl<LicenseKeySet> implements LicenseKeySetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key set model instance should use the <code>LicenseKeySet</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LicenseKeySet";

	public static final Object[][] TABLE_COLUMNS = {
		{"licenseKeySetId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"koroneikiAccountKey", Types.VARCHAR},
		{"accountEntryId", Types.BIGINT}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("licenseKeySetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("koroneikiAccountKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_LicenseKeySet (licenseKeySetId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,koroneikiAccountKey VARCHAR(75) null,accountEntryId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OSB_LicenseKeySet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY licenseKeySet.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_LicenseKeySet.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.customer.license.model.LicenseKeySet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.customer.license.model.LicenseKeySet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.customer.license.model.LicenseKeySet"),
		true);

	public static final long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;

	public static final long KORONEIKIACCOUNTKEY_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseKeySet toModel(LicenseKeySetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseKeySet model = new LicenseKeySetImpl();

		model.setLicenseKeySetId(soapModel.getLicenseKeySetId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setKoroneikiAccountKey(soapModel.getKoroneikiAccountKey());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseKeySet> toModels(LicenseKeySetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseKeySet> models = new ArrayList<LicenseKeySet>(
			soapModels.length);

		for (LicenseKeySetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.customer.license.model.LicenseKeySet"));

	public LicenseKeySetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _licenseKeySetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLicenseKeySetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseKeySetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LicenseKeySet.class;
	}

	@Override
	public String getModelClassName() {
		return LicenseKeySet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LicenseKeySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LicenseKeySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKeySet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LicenseKeySet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LicenseKeySet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LicenseKeySet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LicenseKeySet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LicenseKeySet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LicenseKeySet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LicenseKeySet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LicenseKeySet.class.getClassLoader(), LicenseKeySet.class,
			ModelWrapper.class);

		try {
			Constructor<LicenseKeySet> constructor =
				(Constructor<LicenseKeySet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LicenseKeySet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LicenseKeySet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LicenseKeySet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LicenseKeySet, Object>>();
		Map<String, BiConsumer<LicenseKeySet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LicenseKeySet, ?>>();

		attributeGetterFunctions.put(
			"licenseKeySetId",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getLicenseKeySetId();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseKeySetId",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object licenseKeySetIdObject) {

					licenseKeySet.setLicenseKeySetId(
						(Long)licenseKeySetIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object userIdObject) {

					licenseKeySet.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object userNameObject) {

					licenseKeySet.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object createDateObject) {

					licenseKeySet.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object modifiedDateObject) {

					licenseKeySet.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"koroneikiAccountKey",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getKoroneikiAccountKey();
				}

			});
		attributeSetterBiConsumers.put(
			"koroneikiAccountKey",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet,
					Object koroneikiAccountKeyObject) {

					licenseKeySet.setKoroneikiAccountKey(
						(String)koroneikiAccountKeyObject);
				}

			});
		attributeGetterFunctions.put(
			"accountEntryId",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getAccountEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"accountEntryId",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object accountEntryIdObject) {

					licenseKeySet.setAccountEntryId((Long)accountEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<LicenseKeySet, Object>() {

				@Override
				public Object apply(LicenseKeySet licenseKeySet) {
					return licenseKeySet.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<LicenseKeySet, Object>() {

				@Override
				public void accept(
					LicenseKeySet licenseKeySet, Object nameObject) {

					licenseKeySet.setName((String)nameObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getLicenseKeySetId() {
		return _licenseKeySetId;
	}

	@Override
	public void setLicenseKeySetId(long licenseKeySetId) {
		_licenseKeySetId = licenseKeySetId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getKoroneikiAccountKey() {
		if (_koroneikiAccountKey == null) {
			return "";
		}
		else {
			return _koroneikiAccountKey;
		}
	}

	@Override
	public void setKoroneikiAccountKey(String koroneikiAccountKey) {
		_columnBitmask |= KORONEIKIACCOUNTKEY_COLUMN_BITMASK;

		if (_originalKoroneikiAccountKey == null) {
			_originalKoroneikiAccountKey = _koroneikiAccountKey;
		}

		_koroneikiAccountKey = koroneikiAccountKey;
	}

	public String getOriginalKoroneikiAccountKey() {
		return GetterUtil.getString(_originalKoroneikiAccountKey);
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		_columnBitmask |= ACCOUNTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAccountEntryId) {
			_setOriginalAccountEntryId = true;

			_originalAccountEntryId = _accountEntryId;
		}

		_accountEntryId = accountEntryId;
	}

	public long getOriginalAccountEntryId() {
		return _originalAccountEntryId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LicenseKeySet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseKeySet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LicenseKeySet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseKeySetImpl licenseKeySetImpl = new LicenseKeySetImpl();

		licenseKeySetImpl.setLicenseKeySetId(getLicenseKeySetId());
		licenseKeySetImpl.setUserId(getUserId());
		licenseKeySetImpl.setUserName(getUserName());
		licenseKeySetImpl.setCreateDate(getCreateDate());
		licenseKeySetImpl.setModifiedDate(getModifiedDate());
		licenseKeySetImpl.setKoroneikiAccountKey(getKoroneikiAccountKey());
		licenseKeySetImpl.setAccountEntryId(getAccountEntryId());
		licenseKeySetImpl.setName(getName());

		licenseKeySetImpl.resetOriginalValues();

		return licenseKeySetImpl;
	}

	@Override
	public int compareTo(LicenseKeySet licenseKeySet) {
		int value = 0;

		value = getName().compareToIgnoreCase(licenseKeySet.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LicenseKeySet)) {
			return false;
		}

		LicenseKeySet licenseKeySet = (LicenseKeySet)object;

		long primaryKey = licenseKeySet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalKoroneikiAccountKey = _koroneikiAccountKey;

		_originalAccountEntryId = _accountEntryId;

		_setOriginalAccountEntryId = false;

		_originalName = _name;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseKeySet> toCacheModel() {
		LicenseKeySetCacheModel licenseKeySetCacheModel =
			new LicenseKeySetCacheModel();

		licenseKeySetCacheModel.licenseKeySetId = getLicenseKeySetId();

		licenseKeySetCacheModel.userId = getUserId();

		licenseKeySetCacheModel.userName = getUserName();

		String userName = licenseKeySetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseKeySetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseKeySetCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseKeySetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseKeySetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseKeySetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseKeySetCacheModel.koroneikiAccountKey = getKoroneikiAccountKey();

		String koroneikiAccountKey =
			licenseKeySetCacheModel.koroneikiAccountKey;

		if ((koroneikiAccountKey != null) &&
			(koroneikiAccountKey.length() == 0)) {

			licenseKeySetCacheModel.koroneikiAccountKey = null;
		}

		licenseKeySetCacheModel.accountEntryId = getAccountEntryId();

		licenseKeySetCacheModel.name = getName();

		String name = licenseKeySetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			licenseKeySetCacheModel.name = null;
		}

		return licenseKeySetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LicenseKeySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LicenseKeySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKeySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LicenseKeySet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LicenseKeySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LicenseKeySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKeySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LicenseKeySet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LicenseKeySet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _licenseKeySetId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _koroneikiAccountKey;
	private String _originalKoroneikiAccountKey;
	private long _accountEntryId;
	private long _originalAccountEntryId;
	private boolean _setOriginalAccountEntryId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private LicenseKeySet _escapedModel;

}