/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.customer.license.model.LicenseKey;
import com.liferay.osb.customer.license.model.LicenseKeyModel;
import com.liferay.osb.customer.license.model.LicenseKeySoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LicenseKey service. Represents a row in the &quot;OSB_LicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LicenseKeyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeyImpl
 * @generated
 */
@JSON(strict = true)
public class LicenseKeyModelImpl
	extends BaseModelImpl<LicenseKey> implements LicenseKeyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key model instance should use the <code>LicenseKey</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LicenseKey";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"licenseKeyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedUserId", Types.BIGINT},
		{"modifiedUserName", Types.VARCHAR}, {"modifiedDate", Types.TIMESTAMP},
		{"licenseKeySetId", Types.BIGINT},
		{"assetReceiptLicenseUuid", Types.VARCHAR},
		{"koroneikiAccountKey", Types.VARCHAR},
		{"koroneikiProductPurchaseKey", Types.VARCHAR},
		{"accountEntryId", Types.BIGINT}, {"orderEntryId", Types.BIGINT},
		{"offeringEntryId", Types.BIGINT}, {"licenseEntryId", Types.BIGINT},
		{"productEntryId", Types.BIGINT}, {"supportResponseId", Types.BIGINT},
		{"accountEntryName", Types.VARCHAR},
		{"licenseEntryName", Types.VARCHAR},
		{"licenseEntryType", Types.VARCHAR}, {"licenseVersion", Types.INTEGER},
		{"productEntryName", Types.VARCHAR}, {"productId", Types.VARCHAR},
		{"productVersion", Types.INTEGER},
		{"productVersionLabel", Types.VARCHAR}, {"clusterId", Types.BIGINT},
		{"owner", Types.VARCHAR}, {"maxServers", Types.INTEGER},
		{"maxConcurrentUsers", Types.BIGINT}, {"maxUsers", Types.BIGINT},
		{"maxHttpSessions", Types.INTEGER}, {"sizing", Types.INTEGER},
		{"description", Types.VARCHAR}, {"hostName", Types.VARCHAR},
		{"ipAddresses", Types.VARCHAR}, {"macAddresses", Types.VARCHAR},
		{"serverId", Types.VARCHAR}, {"key_", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"expirationDate", Types.TIMESTAMP},
		{"additionalInfo", Types.VARCHAR}, {"complimentary", Types.BOOLEAN},
		{"active_", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseKeyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("licenseKeySetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetReceiptLicenseUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("koroneikiAccountKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("koroneikiProductPurchaseKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("offeringEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("licenseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportResponseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountEntryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseEntryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseEntryType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseVersion", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("productEntryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productVersion", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("productVersionLabel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clusterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("owner", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("maxServers", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("maxConcurrentUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxHttpSessions", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sizing", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hostName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ipAddresses", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("macAddresses", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serverId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("additionalInfo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("complimentary", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_LicenseKey (uuid_ VARCHAR(75) null,licenseKeyId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedUserId LONG,modifiedUserName VARCHAR(75) null,modifiedDate DATE null,licenseKeySetId LONG,assetReceiptLicenseUuid VARCHAR(75) null,koroneikiAccountKey VARCHAR(75) null,koroneikiProductPurchaseKey VARCHAR(75) null,accountEntryId LONG,orderEntryId LONG,offeringEntryId LONG,licenseEntryId LONG,productEntryId LONG,supportResponseId LONG,accountEntryName VARCHAR(500) null,licenseEntryName VARCHAR(75) null,licenseEntryType VARCHAR(75) null,licenseVersion INTEGER,productEntryName VARCHAR(75) null,productId VARCHAR(75) null,productVersion INTEGER,productVersionLabel VARCHAR(75) null,clusterId LONG,owner VARCHAR(75) null,maxServers INTEGER,maxConcurrentUsers LONG,maxUsers LONG,maxHttpSessions INTEGER,sizing INTEGER,description VARCHAR(255) null,hostName VARCHAR(75) null,ipAddresses STRING null,macAddresses STRING null,serverId STRING null,key_ STRING null,startDate DATE null,expirationDate DATE null,additionalInfo STRING null,complimentary BOOLEAN,active_ BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table OSB_LicenseKey";

	public static final String ORDER_BY_JPQL =
		" ORDER BY licenseKey.active DESC, licenseKey.licenseKeyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_LicenseKey.active_ DESC, OSB_LicenseKey.licenseKeyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.customer.license.model.LicenseKey"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.customer.license.model.LicenseKey"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.customer.license.model.LicenseKey"),
		true);

	public static final long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;

	public static final long ACTIVE_COLUMN_BITMASK = 2L;

	public static final long ASSETRECEIPTLICENSEUUID_COLUMN_BITMASK = 4L;

	public static final long CLUSTERID_COLUMN_BITMASK = 8L;

	public static final long COMPLIMENTARY_COLUMN_BITMASK = 16L;

	public static final long KORONEIKIACCOUNTKEY_COLUMN_BITMASK = 32L;

	public static final long KORONEIKIPRODUCTPURCHASEKEY_COLUMN_BITMASK = 64L;

	public static final long LICENSEENTRYTYPE_COLUMN_BITMASK = 128L;

	public static final long LICENSEKEYSETID_COLUMN_BITMASK = 256L;

	public static final long OFFERINGENTRYID_COLUMN_BITMASK = 512L;

	public static final long PRODUCTENTRYID_COLUMN_BITMASK = 1024L;

	public static final long PRODUCTENTRYNAME_COLUMN_BITMASK = 2048L;

	public static final long PRODUCTID_COLUMN_BITMASK = 4096L;

	public static final long SERVERID_COLUMN_BITMASK = 8192L;

	public static final long USERID_COLUMN_BITMASK = 16384L;

	public static final long UUID_COLUMN_BITMASK = 32768L;

	public static final long LICENSEKEYID_COLUMN_BITMASK = 65536L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseKey toModel(LicenseKeySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseKey model = new LicenseKeyImpl();

		model.setUuid(soapModel.getUuid());
		model.setLicenseKeyId(soapModel.getLicenseKeyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedUserId(soapModel.getModifiedUserId());
		model.setModifiedUserName(soapModel.getModifiedUserName());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLicenseKeySetId(soapModel.getLicenseKeySetId());
		model.setAssetReceiptLicenseUuid(
			soapModel.getAssetReceiptLicenseUuid());
		model.setKoroneikiAccountKey(soapModel.getKoroneikiAccountKey());
		model.setKoroneikiProductPurchaseKey(
			soapModel.getKoroneikiProductPurchaseKey());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setOrderEntryId(soapModel.getOrderEntryId());
		model.setOfferingEntryId(soapModel.getOfferingEntryId());
		model.setLicenseEntryId(soapModel.getLicenseEntryId());
		model.setProductEntryId(soapModel.getProductEntryId());
		model.setSupportResponseId(soapModel.getSupportResponseId());
		model.setAccountEntryName(soapModel.getAccountEntryName());
		model.setLicenseEntryName(soapModel.getLicenseEntryName());
		model.setLicenseEntryType(soapModel.getLicenseEntryType());
		model.setLicenseVersion(soapModel.getLicenseVersion());
		model.setProductEntryName(soapModel.getProductEntryName());
		model.setProductId(soapModel.getProductId());
		model.setProductVersion(soapModel.getProductVersion());
		model.setProductVersionLabel(soapModel.getProductVersionLabel());
		model.setClusterId(soapModel.getClusterId());
		model.setOwner(soapModel.getOwner());
		model.setMaxServers(soapModel.getMaxServers());
		model.setMaxConcurrentUsers(soapModel.getMaxConcurrentUsers());
		model.setMaxUsers(soapModel.getMaxUsers());
		model.setMaxHttpSessions(soapModel.getMaxHttpSessions());
		model.setSizing(soapModel.getSizing());
		model.setDescription(soapModel.getDescription());
		model.setHostName(soapModel.getHostName());
		model.setIpAddresses(soapModel.getIpAddresses());
		model.setMacAddresses(soapModel.getMacAddresses());
		model.setServerId(soapModel.getServerId());
		model.setKey(soapModel.getKey());
		model.setStartDate(soapModel.getStartDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setAdditionalInfo(soapModel.getAdditionalInfo());
		model.setComplimentary(soapModel.isComplimentary());
		model.setActive(soapModel.isActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseKey> toModels(LicenseKeySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseKey> models = new ArrayList<LicenseKey>(soapModels.length);

		for (LicenseKeySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.customer.license.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.customer.license.model.LicenseKey"));

	public LicenseKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _licenseKeyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLicenseKeyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseKeyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LicenseKey.class;
	}

	@Override
	public String getModelClassName() {
		return LicenseKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LicenseKey)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LicenseKey, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LicenseKey, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LicenseKey)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LicenseKey, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LicenseKey, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LicenseKey>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LicenseKey.class.getClassLoader(), LicenseKey.class,
			ModelWrapper.class);

		try {
			Constructor<LicenseKey> constructor =
				(Constructor<LicenseKey>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LicenseKey, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LicenseKey, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LicenseKey, Object>>();
		Map<String, BiConsumer<LicenseKey, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LicenseKey, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object uuidObject) {
					licenseKey.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseKeyId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseKeyId();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseKeyId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseKeyIdObject) {

					licenseKey.setLicenseKeyId((Long)licenseKeyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object userIdObject) {
					licenseKey.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object userNameObject) {

					licenseKey.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object createDateObject) {

					licenseKey.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedUserId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getModifiedUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedUserId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object modifiedUserIdObject) {

					licenseKey.setModifiedUserId((Long)modifiedUserIdObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedUserName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getModifiedUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedUserName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object modifiedUserNameObject) {

					licenseKey.setModifiedUserName(
						(String)modifiedUserNameObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object modifiedDateObject) {

					licenseKey.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseKeySetId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseKeySetId();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseKeySetId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseKeySetIdObject) {

					licenseKey.setLicenseKeySetId((Long)licenseKeySetIdObject);
				}

			});
		attributeGetterFunctions.put(
			"assetReceiptLicenseUuid",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getAssetReceiptLicenseUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"assetReceiptLicenseUuid",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey,
					Object assetReceiptLicenseUuidObject) {

					licenseKey.setAssetReceiptLicenseUuid(
						(String)assetReceiptLicenseUuidObject);
				}

			});
		attributeGetterFunctions.put(
			"koroneikiAccountKey",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getKoroneikiAccountKey();
				}

			});
		attributeSetterBiConsumers.put(
			"koroneikiAccountKey",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object koroneikiAccountKeyObject) {

					licenseKey.setKoroneikiAccountKey(
						(String)koroneikiAccountKeyObject);
				}

			});
		attributeGetterFunctions.put(
			"koroneikiProductPurchaseKey",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getKoroneikiProductPurchaseKey();
				}

			});
		attributeSetterBiConsumers.put(
			"koroneikiProductPurchaseKey",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey,
					Object koroneikiProductPurchaseKeyObject) {

					licenseKey.setKoroneikiProductPurchaseKey(
						(String)koroneikiProductPurchaseKeyObject);
				}

			});
		attributeGetterFunctions.put(
			"accountEntryId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getAccountEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"accountEntryId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object accountEntryIdObject) {

					licenseKey.setAccountEntryId((Long)accountEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"orderEntryId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getOrderEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"orderEntryId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object orderEntryIdObject) {

					licenseKey.setOrderEntryId((Long)orderEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"offeringEntryId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getOfferingEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"offeringEntryId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object offeringEntryIdObject) {

					licenseKey.setOfferingEntryId((Long)offeringEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseEntryId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseEntryId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseEntryIdObject) {

					licenseKey.setLicenseEntryId((Long)licenseEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"productEntryId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getProductEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"productEntryId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object productEntryIdObject) {

					licenseKey.setProductEntryId((Long)productEntryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"supportResponseId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getSupportResponseId();
				}

			});
		attributeSetterBiConsumers.put(
			"supportResponseId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object supportResponseIdObject) {

					licenseKey.setSupportResponseId(
						(Long)supportResponseIdObject);
				}

			});
		attributeGetterFunctions.put(
			"accountEntryName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getAccountEntryName();
				}

			});
		attributeSetterBiConsumers.put(
			"accountEntryName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object accountEntryNameObject) {

					licenseKey.setAccountEntryName(
						(String)accountEntryNameObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseEntryName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseEntryName();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseEntryName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseEntryNameObject) {

					licenseKey.setLicenseEntryName(
						(String)licenseEntryNameObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseEntryType",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseEntryType();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseEntryType",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseEntryTypeObject) {

					licenseKey.setLicenseEntryType(
						(String)licenseEntryTypeObject);
				}

			});
		attributeGetterFunctions.put(
			"licenseVersion",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getLicenseVersion();
				}

			});
		attributeSetterBiConsumers.put(
			"licenseVersion",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object licenseVersionObject) {

					licenseKey.setLicenseVersion((Integer)licenseVersionObject);
				}

			});
		attributeGetterFunctions.put(
			"productEntryName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getProductEntryName();
				}

			});
		attributeSetterBiConsumers.put(
			"productEntryName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object productEntryNameObject) {

					licenseKey.setProductEntryName(
						(String)productEntryNameObject);
				}

			});
		attributeGetterFunctions.put(
			"productId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getProductId();
				}

			});
		attributeSetterBiConsumers.put(
			"productId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object productIdObject) {

					licenseKey.setProductId((String)productIdObject);
				}

			});
		attributeGetterFunctions.put(
			"productVersion",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getProductVersion();
				}

			});
		attributeSetterBiConsumers.put(
			"productVersion",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object productVersionObject) {

					licenseKey.setProductVersion((Integer)productVersionObject);
				}

			});
		attributeGetterFunctions.put(
			"productVersionLabel",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getProductVersionLabel();
				}

			});
		attributeSetterBiConsumers.put(
			"productVersionLabel",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object productVersionLabelObject) {

					licenseKey.setProductVersionLabel(
						(String)productVersionLabelObject);
				}

			});
		attributeGetterFunctions.put(
			"clusterId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getClusterId();
				}

			});
		attributeSetterBiConsumers.put(
			"clusterId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object clusterIdObject) {

					licenseKey.setClusterId((Long)clusterIdObject);
				}

			});
		attributeGetterFunctions.put(
			"owner",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getOwner();
				}

			});
		attributeSetterBiConsumers.put(
			"owner",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object ownerObject) {
					licenseKey.setOwner((String)ownerObject);
				}

			});
		attributeGetterFunctions.put(
			"maxServers",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getMaxServers();
				}

			});
		attributeSetterBiConsumers.put(
			"maxServers",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object maxServersObject) {

					licenseKey.setMaxServers((Integer)maxServersObject);
				}

			});
		attributeGetterFunctions.put(
			"maxConcurrentUsers",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getMaxConcurrentUsers();
				}

			});
		attributeSetterBiConsumers.put(
			"maxConcurrentUsers",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object maxConcurrentUsersObject) {

					licenseKey.setMaxConcurrentUsers(
						(Long)maxConcurrentUsersObject);
				}

			});
		attributeGetterFunctions.put(
			"maxUsers",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getMaxUsers();
				}

			});
		attributeSetterBiConsumers.put(
			"maxUsers",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object maxUsersObject) {

					licenseKey.setMaxUsers((Long)maxUsersObject);
				}

			});
		attributeGetterFunctions.put(
			"maxHttpSessions",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getMaxHttpSessions();
				}

			});
		attributeSetterBiConsumers.put(
			"maxHttpSessions",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object maxHttpSessionsObject) {

					licenseKey.setMaxHttpSessions(
						(Integer)maxHttpSessionsObject);
				}

			});
		attributeGetterFunctions.put(
			"sizing",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getSizing();
				}

			});
		attributeSetterBiConsumers.put(
			"sizing",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object sizingObject) {
					licenseKey.setSizing((Integer)sizingObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object descriptionObject) {

					licenseKey.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"hostName",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getHostName();
				}

			});
		attributeSetterBiConsumers.put(
			"hostName",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object hostNameObject) {

					licenseKey.setHostName((String)hostNameObject);
				}

			});
		attributeGetterFunctions.put(
			"ipAddresses",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getIpAddresses();
				}

			});
		attributeSetterBiConsumers.put(
			"ipAddresses",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object ipAddressesObject) {

					licenseKey.setIpAddresses((String)ipAddressesObject);
				}

			});
		attributeGetterFunctions.put(
			"macAddresses",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getMacAddresses();
				}

			});
		attributeSetterBiConsumers.put(
			"macAddresses",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object macAddressesObject) {

					licenseKey.setMacAddresses((String)macAddressesObject);
				}

			});
		attributeGetterFunctions.put(
			"serverId",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getServerId();
				}

			});
		attributeSetterBiConsumers.put(
			"serverId",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object serverIdObject) {

					licenseKey.setServerId((String)serverIdObject);
				}

			});
		attributeGetterFunctions.put(
			"key",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getKey();
				}

			});
		attributeSetterBiConsumers.put(
			"key",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object keyObject) {
					licenseKey.setKey((String)keyObject);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object startDateObject) {

					licenseKey.setStartDate((Date)startDateObject);
				}

			});
		attributeGetterFunctions.put(
			"expirationDate",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getExpirationDate();
				}

			});
		attributeSetterBiConsumers.put(
			"expirationDate",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object expirationDateObject) {

					licenseKey.setExpirationDate((Date)expirationDateObject);
				}

			});
		attributeGetterFunctions.put(
			"additionalInfo",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getAdditionalInfo();
				}

			});
		attributeSetterBiConsumers.put(
			"additionalInfo",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object additionalInfoObject) {

					licenseKey.setAdditionalInfo((String)additionalInfoObject);
				}

			});
		attributeGetterFunctions.put(
			"complimentary",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getComplimentary();
				}

			});
		attributeSetterBiConsumers.put(
			"complimentary",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(
					LicenseKey licenseKey, Object complimentaryObject) {

					licenseKey.setComplimentary((Boolean)complimentaryObject);
				}

			});
		attributeGetterFunctions.put(
			"active",
			new Function<LicenseKey, Object>() {

				@Override
				public Object apply(LicenseKey licenseKey) {
					return licenseKey.getActive();
				}

			});
		attributeSetterBiConsumers.put(
			"active",
			new BiConsumer<LicenseKey, Object>() {

				@Override
				public void accept(LicenseKey licenseKey, Object activeObject) {
					licenseKey.setActive((Boolean)activeObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLicenseKeyId() {
		return _licenseKeyId;
	}

	@Override
	public void setLicenseKeyId(long licenseKeyId) {
		_licenseKeyId = licenseKeyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getModifiedUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
	}

	@JSON
	@Override
	public String getModifiedUserName() {
		if (_modifiedUserName == null) {
			return "";
		}
		else {
			return _modifiedUserName;
		}
	}

	@Override
	public void setModifiedUserName(String modifiedUserName) {
		_modifiedUserName = modifiedUserName;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLicenseKeySetId() {
		return _licenseKeySetId;
	}

	@Override
	public void setLicenseKeySetId(long licenseKeySetId) {
		_columnBitmask |= LICENSEKEYSETID_COLUMN_BITMASK;

		if (!_setOriginalLicenseKeySetId) {
			_setOriginalLicenseKeySetId = true;

			_originalLicenseKeySetId = _licenseKeySetId;
		}

		_licenseKeySetId = licenseKeySetId;
	}

	public long getOriginalLicenseKeySetId() {
		return _originalLicenseKeySetId;
	}

	@JSON
	@Override
	public String getAssetReceiptLicenseUuid() {
		if (_assetReceiptLicenseUuid == null) {
			return "";
		}
		else {
			return _assetReceiptLicenseUuid;
		}
	}

	@Override
	public void setAssetReceiptLicenseUuid(String assetReceiptLicenseUuid) {
		_columnBitmask |= ASSETRECEIPTLICENSEUUID_COLUMN_BITMASK;

		if (_originalAssetReceiptLicenseUuid == null) {
			_originalAssetReceiptLicenseUuid = _assetReceiptLicenseUuid;
		}

		_assetReceiptLicenseUuid = assetReceiptLicenseUuid;
	}

	public String getOriginalAssetReceiptLicenseUuid() {
		return GetterUtil.getString(_originalAssetReceiptLicenseUuid);
	}

	@JSON
	@Override
	public String getKoroneikiAccountKey() {
		if (_koroneikiAccountKey == null) {
			return "";
		}
		else {
			return _koroneikiAccountKey;
		}
	}

	@Override
	public void setKoroneikiAccountKey(String koroneikiAccountKey) {
		_columnBitmask |= KORONEIKIACCOUNTKEY_COLUMN_BITMASK;

		if (_originalKoroneikiAccountKey == null) {
			_originalKoroneikiAccountKey = _koroneikiAccountKey;
		}

		_koroneikiAccountKey = koroneikiAccountKey;
	}

	public String getOriginalKoroneikiAccountKey() {
		return GetterUtil.getString(_originalKoroneikiAccountKey);
	}

	@JSON
	@Override
	public String getKoroneikiProductPurchaseKey() {
		if (_koroneikiProductPurchaseKey == null) {
			return "";
		}
		else {
			return _koroneikiProductPurchaseKey;
		}
	}

	@Override
	public void setKoroneikiProductPurchaseKey(
		String koroneikiProductPurchaseKey) {

		_columnBitmask |= KORONEIKIPRODUCTPURCHASEKEY_COLUMN_BITMASK;

		if (_originalKoroneikiProductPurchaseKey == null) {
			_originalKoroneikiProductPurchaseKey = _koroneikiProductPurchaseKey;
		}

		_koroneikiProductPurchaseKey = koroneikiProductPurchaseKey;
	}

	public String getOriginalKoroneikiProductPurchaseKey() {
		return GetterUtil.getString(_originalKoroneikiProductPurchaseKey);
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		_columnBitmask |= ACCOUNTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAccountEntryId) {
			_setOriginalAccountEntryId = true;

			_originalAccountEntryId = _accountEntryId;
		}

		_accountEntryId = accountEntryId;
	}

	public long getOriginalAccountEntryId() {
		return _originalAccountEntryId;
	}

	@JSON
	@Override
	public long getOrderEntryId() {
		return _orderEntryId;
	}

	@Override
	public void setOrderEntryId(long orderEntryId) {
		_orderEntryId = orderEntryId;
	}

	@JSON
	@Override
	public long getOfferingEntryId() {
		return _offeringEntryId;
	}

	@Override
	public void setOfferingEntryId(long offeringEntryId) {
		_columnBitmask |= OFFERINGENTRYID_COLUMN_BITMASK;

		if (!_setOriginalOfferingEntryId) {
			_setOriginalOfferingEntryId = true;

			_originalOfferingEntryId = _offeringEntryId;
		}

		_offeringEntryId = offeringEntryId;
	}

	public long getOriginalOfferingEntryId() {
		return _originalOfferingEntryId;
	}

	@JSON
	@Override
	public long getLicenseEntryId() {
		return _licenseEntryId;
	}

	@Override
	public void setLicenseEntryId(long licenseEntryId) {
		_licenseEntryId = licenseEntryId;
	}

	@JSON
	@Override
	public long getProductEntryId() {
		return _productEntryId;
	}

	@Override
	public void setProductEntryId(long productEntryId) {
		_columnBitmask |= PRODUCTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalProductEntryId) {
			_setOriginalProductEntryId = true;

			_originalProductEntryId = _productEntryId;
		}

		_productEntryId = productEntryId;
	}

	public long getOriginalProductEntryId() {
		return _originalProductEntryId;
	}

	@JSON
	@Override
	public long getSupportResponseId() {
		return _supportResponseId;
	}

	@Override
	public void setSupportResponseId(long supportResponseId) {
		_supportResponseId = supportResponseId;
	}

	@JSON
	@Override
	public String getAccountEntryName() {
		if (_accountEntryName == null) {
			return "";
		}
		else {
			return _accountEntryName;
		}
	}

	@Override
	public void setAccountEntryName(String accountEntryName) {
		_accountEntryName = accountEntryName;
	}

	@JSON
	@Override
	public String getLicenseEntryName() {
		if (_licenseEntryName == null) {
			return "";
		}
		else {
			return _licenseEntryName;
		}
	}

	@Override
	public void setLicenseEntryName(String licenseEntryName) {
		_licenseEntryName = licenseEntryName;
	}

	@JSON
	@Override
	public String getLicenseEntryType() {
		if (_licenseEntryType == null) {
			return "";
		}
		else {
			return _licenseEntryType;
		}
	}

	@Override
	public void setLicenseEntryType(String licenseEntryType) {
		_columnBitmask |= LICENSEENTRYTYPE_COLUMN_BITMASK;

		if (_originalLicenseEntryType == null) {
			_originalLicenseEntryType = _licenseEntryType;
		}

		_licenseEntryType = licenseEntryType;
	}

	public String getOriginalLicenseEntryType() {
		return GetterUtil.getString(_originalLicenseEntryType);
	}

	@JSON
	@Override
	public int getLicenseVersion() {
		return _licenseVersion;
	}

	@Override
	public void setLicenseVersion(int licenseVersion) {
		_licenseVersion = licenseVersion;
	}

	@JSON
	@Override
	public String getProductEntryName() {
		if (_productEntryName == null) {
			return "";
		}
		else {
			return _productEntryName;
		}
	}

	@Override
	public void setProductEntryName(String productEntryName) {
		_columnBitmask |= PRODUCTENTRYNAME_COLUMN_BITMASK;

		if (_originalProductEntryName == null) {
			_originalProductEntryName = _productEntryName;
		}

		_productEntryName = productEntryName;
	}

	public String getOriginalProductEntryName() {
		return GetterUtil.getString(_originalProductEntryName);
	}

	@JSON
	@Override
	public String getProductId() {
		if (_productId == null) {
			return "";
		}
		else {
			return _productId;
		}
	}

	@Override
	public void setProductId(String productId) {
		_columnBitmask |= PRODUCTID_COLUMN_BITMASK;

		if (_originalProductId == null) {
			_originalProductId = _productId;
		}

		_productId = productId;
	}

	public String getOriginalProductId() {
		return GetterUtil.getString(_originalProductId);
	}

	@JSON
	@Override
	public int getProductVersion() {
		return _productVersion;
	}

	@Override
	public void setProductVersion(int productVersion) {
		_productVersion = productVersion;
	}

	@JSON
	@Override
	public String getProductVersionLabel() {
		if (_productVersionLabel == null) {
			return "";
		}
		else {
			return _productVersionLabel;
		}
	}

	@Override
	public void setProductVersionLabel(String productVersionLabel) {
		_productVersionLabel = productVersionLabel;
	}

	@JSON
	@Override
	public long getClusterId() {
		return _clusterId;
	}

	@Override
	public void setClusterId(long clusterId) {
		_columnBitmask |= CLUSTERID_COLUMN_BITMASK;

		if (!_setOriginalClusterId) {
			_setOriginalClusterId = true;

			_originalClusterId = _clusterId;
		}

		_clusterId = clusterId;
	}

	public long getOriginalClusterId() {
		return _originalClusterId;
	}

	@JSON
	@Override
	public String getOwner() {
		if (_owner == null) {
			return "";
		}
		else {
			return _owner;
		}
	}

	@Override
	public void setOwner(String owner) {
		_owner = owner;
	}

	@JSON
	@Override
	public int getMaxServers() {
		return _maxServers;
	}

	@Override
	public void setMaxServers(int maxServers) {
		_maxServers = maxServers;
	}

	@JSON
	@Override
	public long getMaxConcurrentUsers() {
		return _maxConcurrentUsers;
	}

	@Override
	public void setMaxConcurrentUsers(long maxConcurrentUsers) {
		_maxConcurrentUsers = maxConcurrentUsers;
	}

	@JSON
	@Override
	public long getMaxUsers() {
		return _maxUsers;
	}

	@Override
	public void setMaxUsers(long maxUsers) {
		_maxUsers = maxUsers;
	}

	@JSON
	@Override
	public int getMaxHttpSessions() {
		return _maxHttpSessions;
	}

	@Override
	public void setMaxHttpSessions(int maxHttpSessions) {
		_maxHttpSessions = maxHttpSessions;
	}

	@JSON
	@Override
	public int getSizing() {
		return _sizing;
	}

	@Override
	public void setSizing(int sizing) {
		_sizing = sizing;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getHostName() {
		if (_hostName == null) {
			return "";
		}
		else {
			return _hostName;
		}
	}

	@Override
	public void setHostName(String hostName) {
		_hostName = hostName;
	}

	@JSON
	@Override
	public String getIpAddresses() {
		if (_ipAddresses == null) {
			return "";
		}
		else {
			return _ipAddresses;
		}
	}

	@Override
	public void setIpAddresses(String ipAddresses) {
		_ipAddresses = ipAddresses;
	}

	@JSON
	@Override
	public String getMacAddresses() {
		if (_macAddresses == null) {
			return "";
		}
		else {
			return _macAddresses;
		}
	}

	@Override
	public void setMacAddresses(String macAddresses) {
		_macAddresses = macAddresses;
	}

	@JSON
	@Override
	public String getServerId() {
		if (_serverId == null) {
			return "";
		}
		else {
			return _serverId;
		}
	}

	@Override
	public void setServerId(String serverId) {
		_columnBitmask |= SERVERID_COLUMN_BITMASK;

		if (_originalServerId == null) {
			_originalServerId = _serverId;
		}

		_serverId = serverId;
	}

	public String getOriginalServerId() {
		return GetterUtil.getString(_originalServerId);
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_key = key;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public String getAdditionalInfo() {
		if (_additionalInfo == null) {
			return "";
		}
		else {
			return _additionalInfo;
		}
	}

	@Override
	public void setAdditionalInfo(String additionalInfo) {
		_additionalInfo = additionalInfo;
	}

	@JSON
	@Override
	public boolean getComplimentary() {
		return _complimentary;
	}

	@JSON
	@Override
	public boolean isComplimentary() {
		return _complimentary;
	}

	@Override
	public void setComplimentary(boolean complimentary) {
		_columnBitmask |= COMPLIMENTARY_COLUMN_BITMASK;

		if (!_setOriginalComplimentary) {
			_setOriginalComplimentary = true;

			_originalComplimentary = _complimentary;
		}

		_complimentary = complimentary;
	}

	public boolean getOriginalComplimentary() {
		return _originalComplimentary;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LicenseKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseKey toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LicenseKey>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseKeyImpl licenseKeyImpl = new LicenseKeyImpl();

		licenseKeyImpl.setUuid(getUuid());
		licenseKeyImpl.setLicenseKeyId(getLicenseKeyId());
		licenseKeyImpl.setUserId(getUserId());
		licenseKeyImpl.setUserName(getUserName());
		licenseKeyImpl.setCreateDate(getCreateDate());
		licenseKeyImpl.setModifiedUserId(getModifiedUserId());
		licenseKeyImpl.setModifiedUserName(getModifiedUserName());
		licenseKeyImpl.setModifiedDate(getModifiedDate());
		licenseKeyImpl.setLicenseKeySetId(getLicenseKeySetId());
		licenseKeyImpl.setAssetReceiptLicenseUuid(getAssetReceiptLicenseUuid());
		licenseKeyImpl.setKoroneikiAccountKey(getKoroneikiAccountKey());
		licenseKeyImpl.setKoroneikiProductPurchaseKey(
			getKoroneikiProductPurchaseKey());
		licenseKeyImpl.setAccountEntryId(getAccountEntryId());
		licenseKeyImpl.setOrderEntryId(getOrderEntryId());
		licenseKeyImpl.setOfferingEntryId(getOfferingEntryId());
		licenseKeyImpl.setLicenseEntryId(getLicenseEntryId());
		licenseKeyImpl.setProductEntryId(getProductEntryId());
		licenseKeyImpl.setSupportResponseId(getSupportResponseId());
		licenseKeyImpl.setAccountEntryName(getAccountEntryName());
		licenseKeyImpl.setLicenseEntryName(getLicenseEntryName());
		licenseKeyImpl.setLicenseEntryType(getLicenseEntryType());
		licenseKeyImpl.setLicenseVersion(getLicenseVersion());
		licenseKeyImpl.setProductEntryName(getProductEntryName());
		licenseKeyImpl.setProductId(getProductId());
		licenseKeyImpl.setProductVersion(getProductVersion());
		licenseKeyImpl.setProductVersionLabel(getProductVersionLabel());
		licenseKeyImpl.setClusterId(getClusterId());
		licenseKeyImpl.setOwner(getOwner());
		licenseKeyImpl.setMaxServers(getMaxServers());
		licenseKeyImpl.setMaxConcurrentUsers(getMaxConcurrentUsers());
		licenseKeyImpl.setMaxUsers(getMaxUsers());
		licenseKeyImpl.setMaxHttpSessions(getMaxHttpSessions());
		licenseKeyImpl.setSizing(getSizing());
		licenseKeyImpl.setDescription(getDescription());
		licenseKeyImpl.setHostName(getHostName());
		licenseKeyImpl.setIpAddresses(getIpAddresses());
		licenseKeyImpl.setMacAddresses(getMacAddresses());
		licenseKeyImpl.setServerId(getServerId());
		licenseKeyImpl.setKey(getKey());
		licenseKeyImpl.setStartDate(getStartDate());
		licenseKeyImpl.setExpirationDate(getExpirationDate());
		licenseKeyImpl.setAdditionalInfo(getAdditionalInfo());
		licenseKeyImpl.setComplimentary(isComplimentary());
		licenseKeyImpl.setActive(isActive());

		licenseKeyImpl.resetOriginalValues();

		return licenseKeyImpl;
	}

	@Override
	public int compareTo(LicenseKey licenseKey) {
		int value = 0;

		value = Boolean.compare(isActive(), licenseKey.isActive());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		if (getLicenseKeyId() < licenseKey.getLicenseKeyId()) {
			value = -1;
		}
		else if (getLicenseKeyId() > licenseKey.getLicenseKeyId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LicenseKey)) {
			return false;
		}

		LicenseKey licenseKey = (LicenseKey)object;

		long primaryKey = licenseKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalLicenseKeySetId = _licenseKeySetId;

		_setOriginalLicenseKeySetId = false;

		_originalAssetReceiptLicenseUuid = _assetReceiptLicenseUuid;

		_originalKoroneikiAccountKey = _koroneikiAccountKey;

		_originalKoroneikiProductPurchaseKey = _koroneikiProductPurchaseKey;

		_originalAccountEntryId = _accountEntryId;

		_setOriginalAccountEntryId = false;

		_originalOfferingEntryId = _offeringEntryId;

		_setOriginalOfferingEntryId = false;

		_originalProductEntryId = _productEntryId;

		_setOriginalProductEntryId = false;

		_originalLicenseEntryType = _licenseEntryType;

		_originalProductEntryName = _productEntryName;

		_originalProductId = _productId;

		_originalClusterId = _clusterId;

		_setOriginalClusterId = false;

		_originalServerId = _serverId;

		_originalComplimentary = _complimentary;

		_setOriginalComplimentary = false;

		_originalActive = _active;

		_setOriginalActive = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseKey> toCacheModel() {
		LicenseKeyCacheModel licenseKeyCacheModel = new LicenseKeyCacheModel();

		licenseKeyCacheModel.uuid = getUuid();

		String uuid = licenseKeyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			licenseKeyCacheModel.uuid = null;
		}

		licenseKeyCacheModel.licenseKeyId = getLicenseKeyId();

		licenseKeyCacheModel.userId = getUserId();

		licenseKeyCacheModel.userName = getUserName();

		String userName = licenseKeyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseKeyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseKeyCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseKeyCacheModel.createDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.modifiedUserId = getModifiedUserId();

		licenseKeyCacheModel.modifiedUserName = getModifiedUserName();

		String modifiedUserName = licenseKeyCacheModel.modifiedUserName;

		if ((modifiedUserName != null) && (modifiedUserName.length() == 0)) {
			licenseKeyCacheModel.modifiedUserName = null;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseKeyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseKeyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.licenseKeySetId = getLicenseKeySetId();

		licenseKeyCacheModel.assetReceiptLicenseUuid =
			getAssetReceiptLicenseUuid();

		String assetReceiptLicenseUuid =
			licenseKeyCacheModel.assetReceiptLicenseUuid;

		if ((assetReceiptLicenseUuid != null) &&
			(assetReceiptLicenseUuid.length() == 0)) {

			licenseKeyCacheModel.assetReceiptLicenseUuid = null;
		}

		licenseKeyCacheModel.koroneikiAccountKey = getKoroneikiAccountKey();

		String koroneikiAccountKey = licenseKeyCacheModel.koroneikiAccountKey;

		if ((koroneikiAccountKey != null) &&
			(koroneikiAccountKey.length() == 0)) {

			licenseKeyCacheModel.koroneikiAccountKey = null;
		}

		licenseKeyCacheModel.koroneikiProductPurchaseKey =
			getKoroneikiProductPurchaseKey();

		String koroneikiProductPurchaseKey =
			licenseKeyCacheModel.koroneikiProductPurchaseKey;

		if ((koroneikiProductPurchaseKey != null) &&
			(koroneikiProductPurchaseKey.length() == 0)) {

			licenseKeyCacheModel.koroneikiProductPurchaseKey = null;
		}

		licenseKeyCacheModel.accountEntryId = getAccountEntryId();

		licenseKeyCacheModel.orderEntryId = getOrderEntryId();

		licenseKeyCacheModel.offeringEntryId = getOfferingEntryId();

		licenseKeyCacheModel.licenseEntryId = getLicenseEntryId();

		licenseKeyCacheModel.productEntryId = getProductEntryId();

		licenseKeyCacheModel.supportResponseId = getSupportResponseId();

		licenseKeyCacheModel.accountEntryName = getAccountEntryName();

		String accountEntryName = licenseKeyCacheModel.accountEntryName;

		if ((accountEntryName != null) && (accountEntryName.length() == 0)) {
			licenseKeyCacheModel.accountEntryName = null;
		}

		licenseKeyCacheModel.licenseEntryName = getLicenseEntryName();

		String licenseEntryName = licenseKeyCacheModel.licenseEntryName;

		if ((licenseEntryName != null) && (licenseEntryName.length() == 0)) {
			licenseKeyCacheModel.licenseEntryName = null;
		}

		licenseKeyCacheModel.licenseEntryType = getLicenseEntryType();

		String licenseEntryType = licenseKeyCacheModel.licenseEntryType;

		if ((licenseEntryType != null) && (licenseEntryType.length() == 0)) {
			licenseKeyCacheModel.licenseEntryType = null;
		}

		licenseKeyCacheModel.licenseVersion = getLicenseVersion();

		licenseKeyCacheModel.productEntryName = getProductEntryName();

		String productEntryName = licenseKeyCacheModel.productEntryName;

		if ((productEntryName != null) && (productEntryName.length() == 0)) {
			licenseKeyCacheModel.productEntryName = null;
		}

		licenseKeyCacheModel.productId = getProductId();

		String productId = licenseKeyCacheModel.productId;

		if ((productId != null) && (productId.length() == 0)) {
			licenseKeyCacheModel.productId = null;
		}

		licenseKeyCacheModel.productVersion = getProductVersion();

		licenseKeyCacheModel.productVersionLabel = getProductVersionLabel();

		String productVersionLabel = licenseKeyCacheModel.productVersionLabel;

		if ((productVersionLabel != null) &&
			(productVersionLabel.length() == 0)) {

			licenseKeyCacheModel.productVersionLabel = null;
		}

		licenseKeyCacheModel.clusterId = getClusterId();

		licenseKeyCacheModel.owner = getOwner();

		String owner = licenseKeyCacheModel.owner;

		if ((owner != null) && (owner.length() == 0)) {
			licenseKeyCacheModel.owner = null;
		}

		licenseKeyCacheModel.maxServers = getMaxServers();

		licenseKeyCacheModel.maxConcurrentUsers = getMaxConcurrentUsers();

		licenseKeyCacheModel.maxUsers = getMaxUsers();

		licenseKeyCacheModel.maxHttpSessions = getMaxHttpSessions();

		licenseKeyCacheModel.sizing = getSizing();

		licenseKeyCacheModel.description = getDescription();

		String description = licenseKeyCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			licenseKeyCacheModel.description = null;
		}

		licenseKeyCacheModel.hostName = getHostName();

		String hostName = licenseKeyCacheModel.hostName;

		if ((hostName != null) && (hostName.length() == 0)) {
			licenseKeyCacheModel.hostName = null;
		}

		licenseKeyCacheModel.ipAddresses = getIpAddresses();

		String ipAddresses = licenseKeyCacheModel.ipAddresses;

		if ((ipAddresses != null) && (ipAddresses.length() == 0)) {
			licenseKeyCacheModel.ipAddresses = null;
		}

		licenseKeyCacheModel.macAddresses = getMacAddresses();

		String macAddresses = licenseKeyCacheModel.macAddresses;

		if ((macAddresses != null) && (macAddresses.length() == 0)) {
			licenseKeyCacheModel.macAddresses = null;
		}

		licenseKeyCacheModel.serverId = getServerId();

		String serverId = licenseKeyCacheModel.serverId;

		if ((serverId != null) && (serverId.length() == 0)) {
			licenseKeyCacheModel.serverId = null;
		}

		licenseKeyCacheModel.key = getKey();

		String key = licenseKeyCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			licenseKeyCacheModel.key = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			licenseKeyCacheModel.startDate = startDate.getTime();
		}
		else {
			licenseKeyCacheModel.startDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			licenseKeyCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			licenseKeyCacheModel.expirationDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.additionalInfo = getAdditionalInfo();

		String additionalInfo = licenseKeyCacheModel.additionalInfo;

		if ((additionalInfo != null) && (additionalInfo.length() == 0)) {
			licenseKeyCacheModel.additionalInfo = null;
		}

		licenseKeyCacheModel.complimentary = isComplimentary();

		licenseKeyCacheModel.active = isActive();

		return licenseKeyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LicenseKey)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LicenseKey)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LicenseKey>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _licenseKeyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private long _modifiedUserId;
	private String _modifiedUserName;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _licenseKeySetId;
	private long _originalLicenseKeySetId;
	private boolean _setOriginalLicenseKeySetId;
	private String _assetReceiptLicenseUuid;
	private String _originalAssetReceiptLicenseUuid;
	private String _koroneikiAccountKey;
	private String _originalKoroneikiAccountKey;
	private String _koroneikiProductPurchaseKey;
	private String _originalKoroneikiProductPurchaseKey;
	private long _accountEntryId;
	private long _originalAccountEntryId;
	private boolean _setOriginalAccountEntryId;
	private long _orderEntryId;
	private long _offeringEntryId;
	private long _originalOfferingEntryId;
	private boolean _setOriginalOfferingEntryId;
	private long _licenseEntryId;
	private long _productEntryId;
	private long _originalProductEntryId;
	private boolean _setOriginalProductEntryId;
	private long _supportResponseId;
	private String _accountEntryName;
	private String _licenseEntryName;
	private String _licenseEntryType;
	private String _originalLicenseEntryType;
	private int _licenseVersion;
	private String _productEntryName;
	private String _originalProductEntryName;
	private String _productId;
	private String _originalProductId;
	private int _productVersion;
	private String _productVersionLabel;
	private long _clusterId;
	private long _originalClusterId;
	private boolean _setOriginalClusterId;
	private String _owner;
	private int _maxServers;
	private long _maxConcurrentUsers;
	private long _maxUsers;
	private int _maxHttpSessions;
	private int _sizing;
	private String _description;
	private String _hostName;
	private String _ipAddresses;
	private String _macAddresses;
	private String _serverId;
	private String _originalServerId;
	private String _key;
	private Date _startDate;
	private Date _expirationDate;
	private String _additionalInfo;
	private boolean _complimentary;
	private boolean _originalComplimentary;
	private boolean _setOriginalComplimentary;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private long _columnBitmask;
	private LicenseKey _escapedModel;

}