/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model.impl;

import com.liferay.osb.customer.license.model.LicenseKeySet;
import com.liferay.osb.customer.license.service.LicenseKeySetLocalServiceUtil;

/**
 * The extended model base implementation for the LicenseKeySet service. Represents a row in the &quot;OSB_LicenseKeySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeySetImpl
 * @see LicenseKeySet
 * @generated
 */
public abstract class LicenseKeySetBaseImpl
	extends LicenseKeySetModelImpl implements LicenseKeySet {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key set model instance should use the <code>LicenseKeySet</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LicenseKeySetLocalServiceUtil.addLicenseKeySet(this);
		}
		else {
			LicenseKeySetLocalServiceUtil.updateLicenseKeySet(this);
		}
	}

}