/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model.impl;

import com.liferay.osb.customer.license.model.LicenseKey;
import com.liferay.osb.customer.license.service.LicenseKeyLocalServiceUtil;

/**
 * The extended model base implementation for the LicenseKey service. Represents a row in the &quot;OSB_LicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeyImpl
 * @see LicenseKey
 * @generated
 */
public abstract class LicenseKeyBaseImpl
	extends LicenseKeyModelImpl implements LicenseKey {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key model instance should use the <code>LicenseKey</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LicenseKeyLocalServiceUtil.addLicenseKey(this);
		}
		else {
			LicenseKeyLocalServiceUtil.updateLicenseKey(this);
		}
	}

}