/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LicenseKeySet service. Represents a row in the &quot;OSB_LicenseKeySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.customer.license.model.impl.LicenseKeySetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.customer.license.model.impl.LicenseKeySetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeySet
 * @generated
 */
@ProviderType
public interface LicenseKeySetModel extends BaseModel<LicenseKeySet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a license key set model instance should use the {@link LicenseKeySet} interface instead.
	 */

	/**
	 * Returns the primary key of this license key set.
	 *
	 * @return the primary key of this license key set
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this license key set.
	 *
	 * @param primaryKey the primary key of this license key set
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the license key set ID of this license key set.
	 *
	 * @return the license key set ID of this license key set
	 */
	public long getLicenseKeySetId();

	/**
	 * Sets the license key set ID of this license key set.
	 *
	 * @param licenseKeySetId the license key set ID of this license key set
	 */
	public void setLicenseKeySetId(long licenseKeySetId);

	/**
	 * Returns the user ID of this license key set.
	 *
	 * @return the user ID of this license key set
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this license key set.
	 *
	 * @param userId the user ID of this license key set
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this license key set.
	 *
	 * @return the user uuid of this license key set
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this license key set.
	 *
	 * @param userUuid the user uuid of this license key set
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this license key set.
	 *
	 * @return the user name of this license key set
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this license key set.
	 *
	 * @param userName the user name of this license key set
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this license key set.
	 *
	 * @return the create date of this license key set
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this license key set.
	 *
	 * @param createDate the create date of this license key set
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this license key set.
	 *
	 * @return the modified date of this license key set
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this license key set.
	 *
	 * @param modifiedDate the modified date of this license key set
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the koroneiki account key of this license key set.
	 *
	 * @return the koroneiki account key of this license key set
	 */
	@AutoEscape
	public String getKoroneikiAccountKey();

	/**
	 * Sets the koroneiki account key of this license key set.
	 *
	 * @param koroneikiAccountKey the koroneiki account key of this license key set
	 */
	public void setKoroneikiAccountKey(String koroneikiAccountKey);

	/**
	 * Returns the account entry ID of this license key set.
	 *
	 * @return the account entry ID of this license key set
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this license key set.
	 *
	 * @param accountEntryId the account entry ID of this license key set
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the name of this license key set.
	 *
	 * @return the name of this license key set
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this license key set.
	 *
	 * @param name the name of this license key set
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LicenseKeySet licenseKeySet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LicenseKeySet> toCacheModel();

	@Override
	public LicenseKeySet toEscapedModel();

	@Override
	public LicenseKeySet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}