/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.license.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LicenseKey service. Represents a row in the &quot;OSB_LicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.customer.license.model.impl.LicenseKeyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.customer.license.model.impl.LicenseKeyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKey
 * @generated
 */
@ProviderType
public interface LicenseKeyModel extends BaseModel<LicenseKey> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a license key model instance should use the {@link LicenseKey} interface instead.
	 */

	/**
	 * Returns the primary key of this license key.
	 *
	 * @return the primary key of this license key
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this license key.
	 *
	 * @param primaryKey the primary key of this license key
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this license key.
	 *
	 * @return the uuid of this license key
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this license key.
	 *
	 * @param uuid the uuid of this license key
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the license key ID of this license key.
	 *
	 * @return the license key ID of this license key
	 */
	public long getLicenseKeyId();

	/**
	 * Sets the license key ID of this license key.
	 *
	 * @param licenseKeyId the license key ID of this license key
	 */
	public void setLicenseKeyId(long licenseKeyId);

	/**
	 * Returns the user ID of this license key.
	 *
	 * @return the user ID of this license key
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this license key.
	 *
	 * @param userId the user ID of this license key
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this license key.
	 *
	 * @return the user uuid of this license key
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this license key.
	 *
	 * @param userUuid the user uuid of this license key
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this license key.
	 *
	 * @return the user name of this license key
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this license key.
	 *
	 * @param userName the user name of this license key
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this license key.
	 *
	 * @return the create date of this license key
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this license key.
	 *
	 * @param createDate the create date of this license key
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this license key.
	 *
	 * @return the modified user ID of this license key
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this license key.
	 *
	 * @param modifiedUserId the modified user ID of this license key
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this license key.
	 *
	 * @return the modified user uuid of this license key
	 */
	public String getModifiedUserUuid();

	/**
	 * Sets the modified user uuid of this license key.
	 *
	 * @param modifiedUserUuid the modified user uuid of this license key
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this license key.
	 *
	 * @return the modified user name of this license key
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this license key.
	 *
	 * @param modifiedUserName the modified user name of this license key
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified date of this license key.
	 *
	 * @return the modified date of this license key
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this license key.
	 *
	 * @param modifiedDate the modified date of this license key
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the license key set ID of this license key.
	 *
	 * @return the license key set ID of this license key
	 */
	public long getLicenseKeySetId();

	/**
	 * Sets the license key set ID of this license key.
	 *
	 * @param licenseKeySetId the license key set ID of this license key
	 */
	public void setLicenseKeySetId(long licenseKeySetId);

	/**
	 * Returns the asset receipt license uuid of this license key.
	 *
	 * @return the asset receipt license uuid of this license key
	 */
	@AutoEscape
	public String getAssetReceiptLicenseUuid();

	/**
	 * Sets the asset receipt license uuid of this license key.
	 *
	 * @param assetReceiptLicenseUuid the asset receipt license uuid of this license key
	 */
	public void setAssetReceiptLicenseUuid(String assetReceiptLicenseUuid);

	/**
	 * Returns the koroneiki account key of this license key.
	 *
	 * @return the koroneiki account key of this license key
	 */
	@AutoEscape
	public String getKoroneikiAccountKey();

	/**
	 * Sets the koroneiki account key of this license key.
	 *
	 * @param koroneikiAccountKey the koroneiki account key of this license key
	 */
	public void setKoroneikiAccountKey(String koroneikiAccountKey);

	/**
	 * Returns the koroneiki product purchase key of this license key.
	 *
	 * @return the koroneiki product purchase key of this license key
	 */
	@AutoEscape
	public String getKoroneikiProductPurchaseKey();

	/**
	 * Sets the koroneiki product purchase key of this license key.
	 *
	 * @param koroneikiProductPurchaseKey the koroneiki product purchase key of this license key
	 */
	public void setKoroneikiProductPurchaseKey(
		String koroneikiProductPurchaseKey);

	/**
	 * Returns the account entry ID of this license key.
	 *
	 * @return the account entry ID of this license key
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this license key.
	 *
	 * @param accountEntryId the account entry ID of this license key
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the order entry ID of this license key.
	 *
	 * @return the order entry ID of this license key
	 */
	public long getOrderEntryId();

	/**
	 * Sets the order entry ID of this license key.
	 *
	 * @param orderEntryId the order entry ID of this license key
	 */
	public void setOrderEntryId(long orderEntryId);

	/**
	 * Returns the offering entry ID of this license key.
	 *
	 * @return the offering entry ID of this license key
	 */
	public long getOfferingEntryId();

	/**
	 * Sets the offering entry ID of this license key.
	 *
	 * @param offeringEntryId the offering entry ID of this license key
	 */
	public void setOfferingEntryId(long offeringEntryId);

	/**
	 * Returns the license entry ID of this license key.
	 *
	 * @return the license entry ID of this license key
	 */
	public long getLicenseEntryId();

	/**
	 * Sets the license entry ID of this license key.
	 *
	 * @param licenseEntryId the license entry ID of this license key
	 */
	public void setLicenseEntryId(long licenseEntryId);

	/**
	 * Returns the product entry ID of this license key.
	 *
	 * @return the product entry ID of this license key
	 */
	public long getProductEntryId();

	/**
	 * Sets the product entry ID of this license key.
	 *
	 * @param productEntryId the product entry ID of this license key
	 */
	public void setProductEntryId(long productEntryId);

	/**
	 * Returns the support response ID of this license key.
	 *
	 * @return the support response ID of this license key
	 */
	public long getSupportResponseId();

	/**
	 * Sets the support response ID of this license key.
	 *
	 * @param supportResponseId the support response ID of this license key
	 */
	public void setSupportResponseId(long supportResponseId);

	/**
	 * Returns the account entry name of this license key.
	 *
	 * @return the account entry name of this license key
	 */
	@AutoEscape
	public String getAccountEntryName();

	/**
	 * Sets the account entry name of this license key.
	 *
	 * @param accountEntryName the account entry name of this license key
	 */
	public void setAccountEntryName(String accountEntryName);

	/**
	 * Returns the license entry name of this license key.
	 *
	 * @return the license entry name of this license key
	 */
	@AutoEscape
	public String getLicenseEntryName();

	/**
	 * Sets the license entry name of this license key.
	 *
	 * @param licenseEntryName the license entry name of this license key
	 */
	public void setLicenseEntryName(String licenseEntryName);

	/**
	 * Returns the license entry type of this license key.
	 *
	 * @return the license entry type of this license key
	 */
	@AutoEscape
	public String getLicenseEntryType();

	/**
	 * Sets the license entry type of this license key.
	 *
	 * @param licenseEntryType the license entry type of this license key
	 */
	public void setLicenseEntryType(String licenseEntryType);

	/**
	 * Returns the license version of this license key.
	 *
	 * @return the license version of this license key
	 */
	public int getLicenseVersion();

	/**
	 * Sets the license version of this license key.
	 *
	 * @param licenseVersion the license version of this license key
	 */
	public void setLicenseVersion(int licenseVersion);

	/**
	 * Returns the product entry name of this license key.
	 *
	 * @return the product entry name of this license key
	 */
	@AutoEscape
	public String getProductEntryName();

	/**
	 * Sets the product entry name of this license key.
	 *
	 * @param productEntryName the product entry name of this license key
	 */
	public void setProductEntryName(String productEntryName);

	/**
	 * Returns the product ID of this license key.
	 *
	 * @return the product ID of this license key
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this license key.
	 *
	 * @param productId the product ID of this license key
	 */
	public void setProductId(String productId);

	/**
	 * Returns the product version of this license key.
	 *
	 * @return the product version of this license key
	 */
	public int getProductVersion();

	/**
	 * Sets the product version of this license key.
	 *
	 * @param productVersion the product version of this license key
	 */
	public void setProductVersion(int productVersion);

	/**
	 * Returns the product version label of this license key.
	 *
	 * @return the product version label of this license key
	 */
	@AutoEscape
	public String getProductVersionLabel();

	/**
	 * Sets the product version label of this license key.
	 *
	 * @param productVersionLabel the product version label of this license key
	 */
	public void setProductVersionLabel(String productVersionLabel);

	/**
	 * Returns the cluster ID of this license key.
	 *
	 * @return the cluster ID of this license key
	 */
	public long getClusterId();

	/**
	 * Sets the cluster ID of this license key.
	 *
	 * @param clusterId the cluster ID of this license key
	 */
	public void setClusterId(long clusterId);

	/**
	 * Returns the owner of this license key.
	 *
	 * @return the owner of this license key
	 */
	@AutoEscape
	public String getOwner();

	/**
	 * Sets the owner of this license key.
	 *
	 * @param owner the owner of this license key
	 */
	public void setOwner(String owner);

	/**
	 * Returns the max servers of this license key.
	 *
	 * @return the max servers of this license key
	 */
	public int getMaxServers();

	/**
	 * Sets the max servers of this license key.
	 *
	 * @param maxServers the max servers of this license key
	 */
	public void setMaxServers(int maxServers);

	/**
	 * Returns the max concurrent users of this license key.
	 *
	 * @return the max concurrent users of this license key
	 */
	public long getMaxConcurrentUsers();

	/**
	 * Sets the max concurrent users of this license key.
	 *
	 * @param maxConcurrentUsers the max concurrent users of this license key
	 */
	public void setMaxConcurrentUsers(long maxConcurrentUsers);

	/**
	 * Returns the max users of this license key.
	 *
	 * @return the max users of this license key
	 */
	public long getMaxUsers();

	/**
	 * Sets the max users of this license key.
	 *
	 * @param maxUsers the max users of this license key
	 */
	public void setMaxUsers(long maxUsers);

	/**
	 * Returns the max http sessions of this license key.
	 *
	 * @return the max http sessions of this license key
	 */
	public int getMaxHttpSessions();

	/**
	 * Sets the max http sessions of this license key.
	 *
	 * @param maxHttpSessions the max http sessions of this license key
	 */
	public void setMaxHttpSessions(int maxHttpSessions);

	/**
	 * Returns the sizing of this license key.
	 *
	 * @return the sizing of this license key
	 */
	public int getSizing();

	/**
	 * Sets the sizing of this license key.
	 *
	 * @param sizing the sizing of this license key
	 */
	public void setSizing(int sizing);

	/**
	 * Returns the description of this license key.
	 *
	 * @return the description of this license key
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this license key.
	 *
	 * @param description the description of this license key
	 */
	public void setDescription(String description);

	/**
	 * Returns the host name of this license key.
	 *
	 * @return the host name of this license key
	 */
	@AutoEscape
	public String getHostName();

	/**
	 * Sets the host name of this license key.
	 *
	 * @param hostName the host name of this license key
	 */
	public void setHostName(String hostName);

	/**
	 * Returns the ip addresses of this license key.
	 *
	 * @return the ip addresses of this license key
	 */
	@AutoEscape
	public String getIpAddresses();

	/**
	 * Sets the ip addresses of this license key.
	 *
	 * @param ipAddresses the ip addresses of this license key
	 */
	public void setIpAddresses(String ipAddresses);

	/**
	 * Returns the mac addresses of this license key.
	 *
	 * @return the mac addresses of this license key
	 */
	@AutoEscape
	public String getMacAddresses();

	/**
	 * Sets the mac addresses of this license key.
	 *
	 * @param macAddresses the mac addresses of this license key
	 */
	public void setMacAddresses(String macAddresses);

	/**
	 * Returns the server ID of this license key.
	 *
	 * @return the server ID of this license key
	 */
	@AutoEscape
	public String getServerId();

	/**
	 * Sets the server ID of this license key.
	 *
	 * @param serverId the server ID of this license key
	 */
	public void setServerId(String serverId);

	/**
	 * Returns the key of this license key.
	 *
	 * @return the key of this license key
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this license key.
	 *
	 * @param key the key of this license key
	 */
	public void setKey(String key);

	/**
	 * Returns the start date of this license key.
	 *
	 * @return the start date of this license key
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this license key.
	 *
	 * @param startDate the start date of this license key
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the expiration date of this license key.
	 *
	 * @return the expiration date of this license key
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this license key.
	 *
	 * @param expirationDate the expiration date of this license key
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the additional info of this license key.
	 *
	 * @return the additional info of this license key
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this license key.
	 *
	 * @param additionalInfo the additional info of this license key
	 */
	public void setAdditionalInfo(String additionalInfo);

	/**
	 * Returns the complimentary of this license key.
	 *
	 * @return the complimentary of this license key
	 */
	public boolean getComplimentary();

	/**
	 * Returns <code>true</code> if this license key is complimentary.
	 *
	 * @return <code>true</code> if this license key is complimentary; <code>false</code> otherwise
	 */
	public boolean isComplimentary();

	/**
	 * Sets whether this license key is complimentary.
	 *
	 * @param complimentary the complimentary of this license key
	 */
	public void setComplimentary(boolean complimentary);

	/**
	 * Returns the active of this license key.
	 *
	 * @return the active of this license key
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this license key is active.
	 *
	 * @return <code>true</code> if this license key is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this license key is active.
	 *
	 * @param active the active of this license key
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LicenseKey licenseKey);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LicenseKey> toCacheModel();

	@Override
	public LicenseKey toEscapedModel();

	@Override
	public LicenseKey toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}