/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.license.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LicenseEntry service. Represents a row in the &quot;Provisioning_LicenseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.provisioning.license.model.impl.LicenseEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.provisioning.license.model.impl.LicenseEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseEntry
 * @generated
 */
@ProviderType
public interface LicenseEntryModel extends BaseModel<LicenseEntry>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a license entry model instance should use the {@link LicenseEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this license entry.
	 *
	 * @return the primary key of this license entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this license entry.
	 *
	 * @param primaryKey the primary key of this license entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this license entry.
	 *
	 * @return the mvcc version of this license entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this license entry.
	 *
	 * @param mvccVersion the mvcc version of this license entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the license entry ID of this license entry.
	 *
	 * @return the license entry ID of this license entry
	 */
	public long getLicenseEntryId();

	/**
	 * Sets the license entry ID of this license entry.
	 *
	 * @param licenseEntryId the license entry ID of this license entry
	 */
	public void setLicenseEntryId(long licenseEntryId);

	/**
	 * Returns the user ID of this license entry.
	 *
	 * @return the user ID of this license entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this license entry.
	 *
	 * @param userId the user ID of this license entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this license entry.
	 *
	 * @return the user uuid of this license entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this license entry.
	 *
	 * @param userUuid the user uuid of this license entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this license entry.
	 *
	 * @return the user name of this license entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this license entry.
	 *
	 * @param userName the user name of this license entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this license entry.
	 *
	 * @return the create date of this license entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this license entry.
	 *
	 * @param createDate the create date of this license entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this license entry.
	 *
	 * @return the modified date of this license entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this license entry.
	 *
	 * @param modifiedDate the modified date of this license entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the product key of this license entry.
	 *
	 * @return the product key of this license entry
	 */
	@AutoEscape
	public String getProductKey();

	/**
	 * Sets the product key of this license entry.
	 *
	 * @param productKey the product key of this license entry
	 */
	public void setProductKey(String productKey);

	/**
	 * Returns the name of this license entry.
	 *
	 * @return the name of this license entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this license entry.
	 *
	 * @param name the name of this license entry
	 */
	public void setName(String name);

	/**
	 * Returns the type of this license entry.
	 *
	 * @return the type of this license entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this license entry.
	 *
	 * @param type the type of this license entry
	 */
	public void setType(String type);

	/**
	 * Returns the version min of this license entry.
	 *
	 * @return the version min of this license entry
	 */
	public int getVersionMin();

	/**
	 * Sets the version min of this license entry.
	 *
	 * @param versionMin the version min of this license entry
	 */
	public void setVersionMin(int versionMin);

	/**
	 * Returns the version max of this license entry.
	 *
	 * @return the version max of this license entry
	 */
	public int getVersionMax();

	/**
	 * Sets the version max of this license entry.
	 *
	 * @param versionMax the version max of this license entry
	 */
	public void setVersionMax(int versionMax);

}