/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model.impl;

import com.liferay.osb.koroneiki.taproot.model.AccountField;
import com.liferay.osb.koroneiki.taproot.service.AccountFieldLocalServiceUtil;

/**
 * The extended model base implementation for the AccountField service. Represents a row in the &quot;Koroneiki_AccountField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountFieldImpl
 * @see AccountField
 * @generated
 */
public abstract class AccountFieldBaseImpl
	extends AccountFieldModelImpl implements AccountField {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account field model instance should use the <code>AccountField</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AccountFieldLocalServiceUtil.addAccountField(this);
		}
		else {
			AccountFieldLocalServiceUtil.updateAccountField(this);
		}
	}

}