create table Provisioning_LicenseEntry (
	mvccVersion LONG default 0 not null,
	licenseEntryId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productKey VARCHAR(75) null,
	name VARCHAR(75) null,
	type_ VARCHAR(75) null,
	versionMin INTEGER,
	versionMax INTEGER
);

create table Provisioning_LicenseKey (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	licenseKeyId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedUserId LONG,
	modifiedUserName VARCHAR(75) null,
	modifiedDate DATE null,
	assetReceiptLicenseUuid VARCHAR(75) null,
	accountKey VARCHAR(75) null,
	productPurchaseKey VARCHAR(75) null,
	licenseEntryId LONG,
	productKey VARCHAR(75) null,
	accountCode VARCHAR(75) null,
	accountName VARCHAR(75) null,
	licenseEntryName VARCHAR(75) null,
	licenseEntryType VARCHAR(75) null,
	licenseVersion INTEGER,
	productName VARCHAR(75) null,
	productId VARCHAR(75) null,
	productVersion INTEGER,
	productVersionLabel VARCHAR(75) null,
	clusterId LONG,
	owner VARCHAR(75) null,
	maxServers INTEGER,
	maxConcurrentUsers LONG,
	maxUsers LONG,
	maxHttpSessions INTEGER,
	sizing INTEGER,
	description VARCHAR(75) null,
	hostName VARCHAR(75) null,
	ipAddresses VARCHAR(75) null,
	macAddresses VARCHAR(75) null,
	serverId VARCHAR(75) null,
	key_ VARCHAR(75) null,
	startDate DATE null,
	expirationDate DATE null,
	additionalInfo VARCHAR(75) null,
	complimentary BOOLEAN,
	active_ BOOLEAN
);