create table Provisioning_LicenseEntry (
	mvccVersion LONG default 0 not null,
	licenseEntryId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productKey VARCHAR(75) null,
	name VARCHAR(75) null,
	type_ VARCHAR(75) null,
	versionMin VARCHAR(75) null,
	versionMax VARCHAR(75) null
);

create table Provisioning_LicenseKey (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	licenseKeyId LONG not null primary key,
	companyId LONG,
	userUuid VARCHAR(75) null,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedUserUuid VARCHAR(75) null,
	modifiedUserName VARCHAR(75) null,
	modifiedDate DATE null,
	assetReceiptLicenseUuid VARCHAR(75) null,
	accountKey VARCHAR(75) null,
	productPurchaseKey VARCHAR(75) null,
	licenseEntryId LONG,
	productKey VARCHAR(75) null,
	accountName VARCHAR(500) null,
	licenseEntryName VARCHAR(75) null,
	licenseEntryType VARCHAR(75) null,
	licenseVersion INTEGER,
	productName VARCHAR(75) null,
	productId VARCHAR(75) null,
	productVersion VARCHAR(75) null,
	clusterId LONG,
	name VARCHAR(75) null,
	owner VARCHAR(75) null,
	maxClusterNodes INTEGER,
	maxServers INTEGER,
	maxConcurrentUsers LONG,
	maxUsers LONG,
	maxHttpSessions INTEGER,
	sizing VARCHAR(75) null,
	description VARCHAR(255) null,
	hostName VARCHAR(75) null,
	ipAddresses STRING null,
	macAddresses STRING null,
	serverId STRING null,
	key_ STRING null,
	startDate DATE null,
	expirationDate DATE null,
	additionalInfo STRING null,
	complimentary BOOLEAN,
	active_ BOOLEAN
);